### PR TITLE
More robust and better error reporting of errors in fetch

### LINKED ISSUE #1437: fetching contracts in perf tests fails sporadically
Example Repro: https://github.com/NomicFoundation/slang/actions/runs/17908206992/job/50913487183

### PR DESCRIPTION
**Pull request by beta-ziliani**
Potentially fixes #1437 although the cause of the failure is unknown. This patch should at least give us better insight to what is the cause.

EDIT: with several successful runs, it seems that the fix was being stricter on the status code. Nevertheless, the rest of the code helps better tracing potential issues that might arise.

### CODE REVIEW

File: crates/solidity/testing/utils/src/fetch.rs [hunk 1]
```diff
@@ -24,13 +27,45 @@ pub fn fetch(address: &str, base_path: &Path) -> Result<()> {
 
     // Try with exponential backoff
     let mut tries = 0;
-    while body.is_err() && tries < 6 {
+    while !body
```
Comment (OmarTawfik) [inline crates/solidity/testing/utils/src/fetch.rs]: The proposed code will fail on invalid JSON without retrying. I suggest:

- using `loop` and `break value` to `get()` only once
- check headers/decode the JSON inside the retry loop
- print errors on every attempt, instead of only the last one, for us to check if the error varies between retries.


```rust
let mut i = 0;
let project = loop {
  i += 1;
  
  match try_fetch_project(&url) {
    Ok(project) => break project,
    Err(err) => {
      println!("Error fetching the project on attempt {i} of {MAX_RETRIES}: {err}");
      if i <= MAX_RETRIES {
        sleep(...);
      } else {
        bail!("Giving up after {i} attempts.");
      }
    }
  }

  // write project to disk
}

fn try_fetch_project(url) {
  // fetch response, check status and headers, and decode JSON in the same retry
}
```

**Review by OmarTawfik — APPROVED** [review]
