### PR TITLE
Fix whitespace in generated Wit interfaces

### LINKED ISSUE #1188: broken indentation in generated TS definitions docs
> @OmarTawfik: the indentation is broken here, but not in cst.wit. I wonder if this is a jco bug?

> @mjoerussell: Not jco itself, but it seems like wit-parser strips whitespace from doc comments.

> @OmarTawfik: In that case, I suggest submitting a PR or an issue at `wit-parser`. It might be easier to fix there than trying to find a workaround on our side.
It is owned by the same org that maintains `jco`, and we might be able to get a quick turnaround there.
>
> - https://github.com/sunfishcode/wasm-tools/tree/main/crates/wit-parser
> - https://github.com/bytecodealliance/wasm-tools/issues/new

_Originally posted by @OmarTawfik in https://github.com/NomicFoundation/slang/pull/1169#discussion_r1877296396_

### PR DESCRIPTION
**Pull request by mjoerussell**
This PR updates our version of jco so that we can integrate [this fix from wasm-tools](https://github.com/bytecodealliance/wasm-tools/pull/1954).

Closes #1188

### CODE REVIEW

**Comment by mjoerussell** [comment]
This is ready once [NomicFoundation/jco#13](https://github.com/NomicFoundation/jco/pull/13) is merged, then I'll update the version of jco in this branch back to `nomic-enhancements-release`.

**Review by OmarTawfik — APPROVED** [review]

File: crates/infra/cli/src/commands/setup/git/mod.rs [hunk 1]
```diff
@@ -12,6 +12,11 @@ pub fn setup_git() {
             .arg("config")
             .property("user.email", "github-actions@users.noreply.github.com")
             .run();
+
+        Command::new("git")
```
Comment (OmarTawfik) [inline crates/infra/cli/src/commands/setup/git/mod.rs:16]: This is now handled by `.gitmodules`. Left over?

**Review by OmarTawfik — CHANGES_REQUESTED** [review]
Since we are merging https://github.com/NomicFoundation/jco/pull/15
That will remove the submodule commit #1225 is updating to, which will break it.
In that case, I suggest holding off on this PR, and updating to the final submodule commit after https://github.com/NomicFoundation/jco/pull/15 is merged.

File: crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-compilation.d.ts [hunk 2]
```diff
@@ -86,7 +96,12 @@ export class File {
  *
  * @internal
  */
+
```
Comment (OmarTawfik) [inline crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-compilation.d.ts:99]: I think we also need to change the `branch` in `.gitmodules` to `nomic`.

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -55,6 +55,7 @@ jobs:
   # We cannot run the full CI in devcontainers, as we will run out of disk space in GitHub Actions.
   # Instead, we just validate the devcontainer is built correctly by running a minimal check below.
   validate-devcontainer:
+    needs: "ci"
```
Comment (OmarTawfik) [inline .github/workflows/ci.yml:58]: Is this still needed? I tested CI without it, and it is passing ([run](https://github.com/OmarTawfik-forks/slang/actions/runs/13449971093)).

Comment (OmarTawfik) [reply .github/workflows/ci.yml:58]: re: your earlier comment about multiple jobs in the same workflow having the same disk size limitation:
I don't think both jobs are necessarily executed on the same GitHub-hosted runner. They are assigned at random based on availability in Azure.
The sanctuary workflow is build/running Slang in 32 concurrent jobs without any failures.

**Review by OmarTawfik — CHANGES_REQUESTED** [review]
Left a couple of suggestions. Thanks!

**Review by OmarTawfik — APPROVED** [review]
